function [ rot, tra ] = f_read_transfor_matrix( makertxt )
%f_read_maker_location: This function is used to load and read original
%                       transformation matrix generated by ARToolKits
%   input:
%         makertxt: the path of txt file that contains the original matrix
%   output:
%         rot: rotation matrix
%         tra: transformation matrix

%example: makertxt
%0.125349 0.034898 0.991499 -184.110893 
%0.763440 -0.641634 -0.073933 64.829444 
%0.633599 0.766217 -0.107071 339.780097 

%rot
%3 3
%0.125349 0.034898 0.991499
%0.763440 -0.641634 -0.073933
%0.633599 0.766217 -0.107071

%tra
%1 3
%-184.110893
%64.829444
%339.780097

fidin = fopen(makertxt,'r');

mycount = 1;
tempsave = zeros(3,4);
while ~feof(fidin)
    tline = fgetl(fidin);
    tline = regexp(tline,' ','split');
    for i = 1:4
        tempsave(mycount,i) = str2double(tline{i});
    end
    mycount = mycount + 1;
end
fclose(fidin);

rot = tempsave(:,1:3);
tra = tempsave(:,4);
end